source 'https://rubygems.org'

gem 'rails', '4.0.1.rc4'
gem 'sqlite3'

gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'

gem 'ember-rails'
gem 'ember-source', '1.1.2'

gem "thin"
group :development do
  gem "quiet_assets"
  gem "pry-rails"
end

gem "active_model_serializers", :github => "rails-api/active_model_serializers", :branch => "rewrite"
